# Generated by Django 4.0.4 on 2022-05-18 06:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Income_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('income_per_annum', models.FloatField(blank=True, default=None)),
                ('savings_per_annum', models.FloatField(blank=True, default=None)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
            ],
        ),
    ]
